### ISSUE TITLE
Display download url

### ISSUE THREAD

**Issue by pimdo** [uintdev/qrserv#14]
Tried the app to download an image to my laptop quickly on local network
Probably the QR code has it, but it is not possible to scan that code on laptop.
found the QR code after click on share.

I think these improvements can make this app very useful:
1. Display the full url (`http://<ip>:<port>/[optional path]`) it will be possible to type it on the client side
2. Show a checksum (md5, etc) to verify file on the other end
3. Move the select button to the middle. Had to try 3 different buttons to figure out which one is the main!

Thanks btw

**Comment by uintdev** [comment]
Hi.

1. On some devices, the share sheet does show the full path. Issue is, some don’t.
I do want to try to avoid using up too much space in the UI (especially if the file name is set to show in the path, which can be very long). Perhaps press and holding the QR code should show a tooltip with the full URL (that can be dismissed on further user touch input)?

2. My concern about doing that has always been that it would take time to come up with a hash when targeting large files. I could test the idea, but I’d want to make sure that it won’t impact the user experience (much).
A fine compromise might be having settings that stick for the app, although I’m still debating to this day if the app should have persistent configurable settings. Mainly because it’s supposed to be kept simple in concept.

3. The idea with that is that many apps have the main floating action button on the right, and that the server shutdown button would appear on the left side anyway.
Despite that, as long as it still looks decent, I would try moving it to the center. I personally would find it more ergonomic to use that way.


I’m currently going to be out for a couple weeks, so I won’t be able to do much in terms of development during that time. But I do have a few potential improvements in mind to get in place for a future release shortly after. 🙂

**Comment by uintdev** [comment]
Happened to have a physical device around to test with, a pixel device even. Decided to make some of the improvements (on the test build I have).
1. The import file FAB was moved to the center (through a slightly hacky method, just to get it to align correctly)
2. Press and holding the QR code shows the full URL
    - Decided on press and hold rather than tap, because tap does not give haptic feedback

There is another experimental improvement I'm trying to get working, and it kind of works. Holding some commits back as I investigate some unusual behaviour from that. It's going to be somewhat important, considering direct access to user storage is a thing now.

**Comment by uintdev** [comment]
Hi. I've just released v2.3.0, which should at least cover 1 and 3.

**Comment by uintdev** [comment]
Closing as part of clean up. Even though the second suggestion is a bit of a tricky one without having some sort of compromise (having to wait for the hash to be calculated) and so can't really see myself implementing it in this case, the others were at least implemented and I do find those to be very nice touches. So thanks for the suggestions. 👍.
